blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}#readme
    about: Read the documentation
